/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Material } from '../models/material';
export interface Bom {
  materials?: Array<Material>;

  /**
   * the name of the article
   */
  name?: string;
}
