/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FileSystem {
  children?: Array<FileSystem>;

  /**
   * the current folder name
   */
  name?: string;

  /**
   * the path to the folder
   */
  path?: string;
  type?: 'file' | 'folder';
}
