/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FullBom {
  children?: Array<FullBom>;

  /**
   * the name of the article
   */
  name?: string;

  /**
   * the article number
   */
  number?: string;
}
