 
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Material {

  /**
   * the name of the article
   */
  name?: string;

  /**
   * the article number
   */
  number?: string;
}
